[versions]
minSdk = "23"
compileSdk = "33"
targetSdk = "33"

androidgradleplugin = "8.11.1"
kotlin = "1.8.22"
kotlinxcoroutines = "1.7.2"
ktlint = "0.50.0"
sdp_version = "1.1.1"

[libraries]
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version = "1.7.2" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.6.1" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version = "1.9.0" }
androidx-exifinterface = { module = "androidx.exifinterface:exifinterface", version = "1.3.6" }
androidx-fragment-testing = { module = "androidx.fragment:fragment-testing", version = "1.6.0" }
androidx-test-junit = { module = "androidx.test.ext:junit", version = "1.1.5" }
junit = { module = "junit:junit", version = "4.13.2" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxcoroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxcoroutines" }
leakcanary-android = { module = "com.squareup.leakcanary:leakcanary-android", version = "2.12" }
material = { module = "com.google.android.material:material", version = "1.9.0" }
mock = { module = "io.mockk:mockk", version = "1.13.5" }
plugin-android-cache-fix = { module = "org.gradle.android.cache-fix:org.gradle.android.cache-fix.gradle.plugin", version = "2.7.2" }
plugin-androidgradleplugin = { module = "com.android.tools.build:gradle", version.ref = "androidgradleplugin" }
plugin-dokka = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version = "1.8.20" }
plugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
plugin-licensee = { module = "app.cash.licensee:licensee-gradle-plugin", version = "1.7.0" }
plugin-paparazzi = { module = "app.cash.paparazzi:paparazzi-gradle-plugin", version = "1.3.0" }
plugin-publish = { module = "com.vanniktech:gradle-maven-publish-plugin", version = "0.29.0" }
robolectric = { module = "org.robolectric:robolectric", version = "4.9" }
timber = { module = "com.jakewharton.timber:timber", version = "5.0.1" }
#SDP-SSP
sdp = { module = "com.intuit.sdp:sdp-android", version.ref = "sdp_version" }
ssp = { module = "com.intuit.ssp:ssp-android", version.ref = "sdp_version" }

[plugins]
codequalitytools = { id = "com.vanniktech.code.quality.tools", version = "0.24.0" }
dependencygraphgenerator = { id = "com.vanniktech.dependency.graph.generator", version = "0.8.0" }

[bundles]
sdpSsp = ["sdp", "ssp"]
